### PR TITLE
Native curl mode

### LINKED ISSUE #7: exact/approiximate Mode for `to_curl/2`
I have been thinking already about doing this kind of processing. Woytek mentioned converting `-H accept_encoding...` to `--compressed` instead of the header version [here](https://x.com/wojtekmach/status/1795673299630141872) but I am hesitant. Why? Because this isn't the request that Req is sending. So I think there are two modes here perhaps. One is "exact" mode, like the request exactly as Req is going to send it (or as close as we can get). And the second is the "approximate" mode (for lack of better terminology), which converts things like basic auth to `-u` and a compression header to `--compressed.

There is then also the question of implementation. The code, as written here, won't work for all cases. Someone could, for instance, add their own auth header, or define a step that does something with the auth option.

I am wondering if we should pull these changes out into a new PR for now. Then we can continue to discuss and refine the hard part but still merge the easy parts for now.

_Originally posted by @derekkraan in https://github.com/derekkraan/curl_req/pull/5#discussion_r1628882584_

### PR DESCRIPTION
**Pull request by kevinschweikert**
Closes #7 

This will now use the native curl compression option and native curl user agent for the command generation, as discussed in the linked issue. Hope you agree with my naming choices, but feel free to make changes!
I've also upgraded Req to the latest version.

### CODE REVIEW

**Comment by derekkraan** [comment]
This is looking great!

I am still kind of torn on `mode` vs `style`. Can you tell me why you like `mode` better?

**Comment by kevinschweikert** [comment]
My though was that `style` could be confused with the flags (style). But I agree, mode doesn't fit perfectly either. What about `flavour`?

**Comment by derekkraan** [comment]
I do like flavour. Let's let it marinade for a day or two.

**Comment by derekkraan** [comment]
Let's do `flavour`, but also support `flavor`, the American English spelling.

What do you think?

**Comment by kevinschweikert** [comment]
I like it! I will implement the changes soon!

**Comment by kevinschweikert** [comment]
I've updated the PR with the changes to `flavor`/`flavor` and i snuck in a small change to support the `--compressed` flag as well in the parser

**Comment by derekkraan** [comment]
Looks great, thanks for this :)

**Pull request merged**
